### PR TITLE
Split item/itemVariant search

### PR DESCRIPTION
**Pull request by cghislai**
Split *search as well

### CODE REVIEW

**Comment by ymajoros** [comment]
Why do you want to split that? At least, have WsItemVarianSearch embed WsItemSearch, as 90% is common.

But will you ever need to search for an item, or will you just search for item variants anyway?

I'd prefer to do those kind of things, to avoid going back and forth.

**Comment by cghislai** [comment]
In the product list (product->list) `Item` are listed.
When editing an `Item`, its `ItemVariant` are displayed, allowing to add/remove some.

When displaying the items for a sale, `ItemVariant` are listed.

I thought of embedding, maybe is it better.

**Comment by ymajoros** [comment]
Ok, I guess it makes some sense ;-)

Let's embed later. Anyway, do you really need this right now? To me, you
can just use the same search for now - just remind to not use
itemVariantRef for an Item. Do you think this will work?

Ok to change it if we embed ItemSearch in ItemVariantSearch. Otherwhise,
you're splitting the code in StockService that I just deduplicated, just to
change that whenever you embed ItemSearch again.

Le ven. 4 sept. 2015 à 15:03, cghislai <notifications@github.com> a écrit :

> In the product list (product->list) Item are listed.
> When editing an Item, its ItemVariant are displayed, allowing to
> add/remove some.
>
> When displaying the items for a sale, ItemVariant are listed.
>
> I thought of embedding, maybe is it better.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Valuya/comptoir/pull/70#issuecomment-137730172>.
>
-- 
Yannick Majoros
Valuya sprl

**Comment by cghislai** [comment]
Closing in favor of #72

**Pull request closed without merging**
